### ISSUE TITLE
Better fullnames

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#49] opened 2019-02-04 13:30 UTC
I think `Particle.fullname` should return better names. Some examples.

| name | fullname | expected fullname |
|------| ----------| -------------------|
|gamma | gamma0| gamma |
|p | p+ | p |
|u| u~+2/3| u~ |
|W| W-|  W-|

**Comment by HDembinski** [comment] 2019-02-04 13:55
Client code that I use, probably can be improved. Only a small subset of all particle names use the notion "bar" to distinguish particle from antiparticle. For most particles it is sufficient to give the charge.
```
            if abs(p.pid) in {1, 2, 3, 4, 5, 6, 12, 14, 16, 2212, 2112}:
                if p_db.bar:
                    pname += "~"
            elif p.pid in {21, 22, 23}:
                pass
            else:
                pname += {2: "++", 1: "+", 0: "0", -1: "-", -2: "--"}.get(p_db.three_charge / 3)
```
Particles which are their own antiparticles should be better detected...

**Comment by eduardo-rodrigues** [comment] 2019-02-04 14:51
Hi @HDembinski, funny enough I have been looking at the same issues.
I agree that the names need to be improved.

The problem is a bit more profound, I think, and I need to discuss with @henryiii on how to improve things from inside-out. For a start, some of the attributes of the Particle class are a 1-to-1 match to the fields of the PDG table. I think we do not need to expose all that to the user. BTW, the reason why some properties do not have docstrings, as you point out in https://github.com/scikit-hep/particle/issues/50, comes from a limitation in attrs, which does not provide an easy way to add a docstring to attr.ib().
Take the example of name and fullname. name can be the same for entries which correspond to particles with more than one charge possible; say a rho. I would make name hidden/private and would expose fullname as name … There is more to it here but let me now try and write it all down. Better discuss in person …


On something related: we also need to have programmatic_name match the names we defined in the literals. That seems the best option to me.

This all needs some work. It won't take 1 day to get it all improved. It will be a great improvement, though ... which explains why I've been looking at the same things as you ... ;-)

**Comment by henryiii** [comment] 2019-02-04 15:25
Docstrings can only be attached to classes or members of classes, but not to instance variables, which is what attrs is. That is, in this case `Simple.x` can have a docstring, but it is incorrect design, it is not a class instance:

```python
class Simple:
    x = something
```

While in this example, value.x cannot have a docstring, but is correct design:

```
class Simple:
    def __init__(self, something):
        self.x = something

value = Simple(something)
```

What you can do, however, is handroll documentation as part of the class docs (and attrs may eventually have a way to generate this, that is technically possible but a bit tricky).

There is a property or two that could be quite useful in cleaning up the fullname. It's worth some effort to see what we can do.

**Comment by henryiii** [comment] 2019-02-04 15:26
Hey, we didn't even have quarks added to Particle until quite recently :)

**Comment by eduardo-rodrigues** [comment] 2019-02-07 17:05
Closed via https://github.com/scikit-hep/particle/pull/51.

**Closed by eduardo-rodrigues** 2019-02-07 17:05 UTC
